import os
import sys
import tempfile

import cohere

from exec_helper import execute

template = """
&module somefile.slop
-- You get files that are imported as part of what is sent to you.

-*
THIS IS JUST AN EXAMPLE OF CODE
THE USER-CREATED CODE DOES NOT HAVE
TO INCLUDE EVERY PIECE OF FUNCTIONALITY
INCLUDED IN THIS **TEMPLATE** FOR YOU TO USE.
*-

// Comment - docstrings
-- Comment - standard
-* Comment *- - standard
/* Comment */ - docstrings

-- The * makes a function public
/*
    Print Hello World 2 times.
*/
function * hello_world(
    &unused: string some_argument,
    &unused: string other_arg
) {
    w("Hello World!\\n")  -* Writes something to stdout
    wln("Hello World")       Writes to stdout with a newline *-
}

constant ConstsUsePascalCaseInSlopper = true
variable varsUseCamelCase = false

&create_type Something struct {
    smth: string
    smh: boolean
}

if (true) {
    -- Example if statement
    hello_world()
} or (varsUseCamelCase) {
    -- Equivalent of elif
} whatever {
    -- Equivalent of else
}

-- Inline function.
// Say hello to the user.
function &in hello(string name) {
    w(fm"Hello %s", name)
}

-- If something is not mentioned here, default to the C language, its syntax, etc.
"""


def get_user_api_key() -> str:
    print("checking for cohere api key... ", end="")
    key = ""
    try:
        with open(os.path.expanduser("~/.config/cohere_key"), "r") as key_file:
            key = key_file.read()
        print("\033[92mok\033[0m")
    except Exception:
        print()  # the last print did not have a newline
        print("\033[91mNo Cohere API key found.\033[0m")
        print(
            "Go to \033[1mhttps://dashboard.cohere.com/api-keys\033[0m and create one."
        )
        print(
            "\033[93mWarning: the API key is stored in a local file (~/.config/cohere_key). Please be careful\033[0m"
        )
        key = input("Then copy it here: ")
        with open(os.path.expanduser("~/.config/cohere_key"), "w") as key_file:
            key_file.write(key)

    if key == "":
        print("\033[91mNo API key entered, or an internal error occured.\033[0m")
        sys.exit(1)
    elif not key.startswith("cohere_"):
        print("\033[91mInvalid API key entered.\033[0m")
        sys.exit(1)

    return key


def get_imports(code: str) -> str:
    """
    Get imports of a Slopper file.

    return -> string ready for the AI, like:
        Detected imported file: lib.slop:
            ...code...

    arg -> code: str - The code
    """

    output = "If this is empty, ignore it, no imports are included.\n"

    lines = code.splitlines()
    for line in lines:
        # Modules in slopper are defined like:
        # &module file.slop
        if line.startswith("&module"):
            if len(line.split(" ")) == 1:
                print("\033[93;1mWarning\033[0m: invalid import, skipping")
                continue

            file = line.split(" ")[1]
            content = ""
            with open(file, "r") as f:
                content = f.read()

            output += f"\nFile: {file}\n--- Content: ---\n{content}\n--- END ---\n\n"

    return output


def output_asm(api_key: str, code: str, verbose: bool = False) -> str:
    """
    Output assembly generated by Cohere.

    return -> string ready for assembling

    arg ->
        api_key: str - the Cohere API key
        code: str - the code to translate
    """

    print("sending code to ai...")
    co = cohere.ClientV2(api_key)
    response = co.chat(
        model="command-a-plus-05-2026",
        messages=[
            cohere.UserChatMessageV2(
                role="user",
                content=f"""**slopper**
# Introduction
You are part of a compiler for a language called Slopper.
You take in some code and translate it to x86_64 Linux AT&T assembly.
You must include everything, including the entry symbol _start.
Your code will segfault if you won't.
---
This is some template code in Slopper:
{template}
---
Files get imported using the &module keyword; you will also receive
a section of this text which includes contents of all the files included.

# Important instructions
* **NEVER** write anything else other than the code. This includes
  Markup formatted text, since that is not a part of assembly.
  This also includes building instructions or tips.
* You **MUST ALWAYS** simply return the code, in one file.
* **ALWAYS** understand that the code is sent straight to an assembler.
* If the code has something you would say is an error:
  only make the message start with "%slopper_error: <The error description>"
* Include no comments as this code is not meant to be read by anyone else

# The user code
* If the code has something you would say is an error:
  only make the message start with "%slopper_error: <The error description>"
* The code is pasted from what the user inputted; if it contains an error, do
  not try to fix it, act like a normal compiler with the isntructions above.
  For example, if the user sends random giberrish, just say something like:
      %slopper_error: invalid code at line 1

{code}

# The imports section
{get_imports(code)}

# Bottom line
NEVER EVER INCLUDE ANYTHING ELSE OTHER THAN THE CODE. NOTHING. NOT A SINGLE WORD.
NOT A CODEBLOCK (```). IF YOU INCLUDE ANYTHING ELSE, THE SYSTEM WILL FAIL.
                """,
            )
        ],
    )

    thinking = ""
    output = ""
    for item in response.message.content:
        if item.type == "thinking":
            thinking = item.thinking
        elif item.type == "text":
            output = item.text
    print(f"  thinking: wrote {len(thinking.splitlines())} lines")
    if verbose:
        print(thinking)

    print(f"generated assembly: wrote {len(output.splitlines())} lines")
    if verbose:
        print(output)

    if output.startswith("%slopper_error"):
        print(f"\033[91mError: {output.replace('%slopper_error:', '')}\033[0m")
        sys.exit(1)

    return output


def compile_to_outfile(code: str, outfile: str):
    code_file = tempfile.NamedTemporaryFile(mode="w+", delete=True)
    code_file.write(code)
    filename = code_file.name

    execute(f"as -o program.o {filename}")
    execute(f"ld -o {outfile} program.o")

    print(f"\033[92mCreated output {outfile}!\033[0m")

    code_file.close()
